version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NPM_REGISTRY: "https://registry.npmmirror.com/"
    volumes:
      - "./frontend/src:/usr/share/nginx/html/src"
      - "./frontend/public:/usr/share/nginx/html"
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      NODE_ENV: "development"
      API_URL: "http://backend:3000/api"
      DEV_MODE: "1"
    restart: unless-stopped

 